schema = 3

[mod]
  [mod.'github.com/buger/jsonparser']
    version = 'v1.2.0'
    hash = 'sha256-CiwV8UFYw2PnnyUoRojiVLq+MlKJ/aviufLcRi1GLbw='

  [mod.'github.com/google/go-github/v87']
    version = 'v87.0.0'
    hash = 'sha256-zi90MiU1JilBh8dMjcNE4BvhwrMLpmcISTRaL6LNqfs='

  [mod.'github.com/google/go-querystring']
    version = 'v1.2.0'
    hash = 'sha256-F/Ve4oDaEqho8RryvdGSRR22/DbYHWZQa6M60n6oSYM='

  [mod.'github.com/gorilla/mux']
    version = 'v1.8.1'
    hash = 'sha256-nDABvAhlYgxUW2N/brrep7NkQXoSGcHhA+XI4+tK0F0='

  [mod.'golang.org/x/mod']
    version = 'v0.36.0'
    hash = 'sha256-ZhyOvy9ptbV+pna/CNyQFr5cKRn5O+B2QzkQAISKgco='

  [mod.'golang.org/x/text']
    version = 'v0.37.0'
    hash = 'sha256-8XDOnlPIybcDRy89fkjG5VqtIt5Ku+LmaqYhgKl7i1E='

  [mod.'golang.org/x/time']
    version = 'v0.15.0'
    hash = 'sha256-5D24A65wn7k93Jj3+918UKjB9ccmGHPBEqjD2XDB92E='
